# Basic
title: Kwin Lee 
subtitle: CARCH-CAS
welcome_message: <a href=" " target="_blank">Download the resume</a>
description:  a PhD student in VIPL-ICT-CAS working on computer vision especially scene understanding. Take a picture and in no time the computer may tell you what are in the picture and where it happens, even a story about it. Sounds amazing, right? Besides my academic life, I have so many hobbies like singing, running etc. I'm also a Japanese language learner for over 7 years.


creator: <a href="http://onev.cat">@onevcat</a>

url: "http://vno.onevcat.com"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: red

# The blog button should not be removed.
blog_button:
    title: Blog
    description: Visit blog

# Navigation buttons in the front page.
nav:
    - {title: Projects, description: My Projects, url: 'http://project.onevcat.com'}
    - {title: Resume, description: A button, url: 'http://myresume.likun.tech'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: vno-jekyll
    # duoshuo: 
    
# Social
social:
    weibo: sdulikun
    github:  
    twitter:  
    gplus:  
    mail: sdulikun@163.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host

theme: jekyll-theme-cayman
